## Seminar 3

In [1]:
print("Hello world!")

Hello world!


In [3]:
import numpy as np

In [4]:
b=[1,2,3]

In [5]:
b?

Type:        list
String form: [1, 2, 3]
Length:      3
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.


In [6]:
b

[1, 2, 3]

In [7]:
?b

Type:        list
String form: [1, 2, 3]
Length:      3
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.


In [8]:
print?

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


In [13]:
def suma(a,b):
    """
    functia calculeaza suma lui a si b
    params: a: primul numar
    params: b: al doilea numar
    """
    return a+b

In [14]:
suma(7,8)

15

In [16]:
suma(2,3)

5

In [17]:
suma?

Signature: suma(a, b)
Docstring:
functia calculeaza suma lui a si b
params: a: primul numar
params: b: al doilea numar
File:      c:\users\maria\appdata\local\temp\ipykernel_14332\3504595087.py
Type:      function


In [19]:
a=4
# a=5
suma(a,6)

10

In [20]:
suma??

Signature: suma(a, b)
Source:   
def suma(a,b):
    """
    functia calculeaza suma lui a si b
    params: a: primul numar
    params: b: al doilea numar
    """
    return a+b
File:      c:\users\maria\appdata\local\temp\ipykernel_14332\3504595087.py
Type:      function


In [21]:
%who

a	 b	 np	 suma	 


In [22]:
%whos

Variable   Type        Data/Info
--------------------------------
a          int         4
b          list        n=3
np         module      <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
suma       function    <function suma at 0x0000022295EFF4C0>


In [23]:
%pwd

'C:\\Users\\maria\\OneDrive\\Desktop\\MASTER\\AN1\\SEM1\\Statistica inferentiala pe calculator\\Lab'

In [26]:
%timeit suma(1,2)

250 ns ± 2.94 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## python

In [28]:
a=[1,2,3]

In [29]:
b=a

In [30]:
b

[1, 2, 3]

In [31]:
a

[1, 2, 3]

In [32]:
a.append(5)

In [33]:
a

[1, 2, 3, 5]

In [34]:
b

[1, 2, 3, 5]

In [35]:
c=a.copy()

In [36]:
c

[1, 2, 3, 5]

In [38]:
a[0]=1000

In [39]:
a

[1000, 2, 3, 5]

In [40]:
b

[1000, 2, 3, 5]

In [41]:
c

[1, 2, 3, 5]

In [42]:
n=10333333628882718721772732631736936378909876543332618927656463

In [43]:
n

10333333628882718721772732631736936378909876543332618927656463

In [44]:
n/2

5.166666814441359e+60

In [45]:
5/3

1.6666666666666667

In [46]:
5//3

1

In [47]:
2**3

8

In [48]:
a='ceva text'

In [49]:
a

'ceva text'

In [50]:
print(a)

ceva text


In [51]:
print(a,b)

ceva text [1000, 2, 3, 5]


In [53]:
print(a,b,c)

ceva text [1000, 2, 3, 5] [1, 2, 3, 5]


In [55]:
print(a+' alt text')

ceva text alt text


In [57]:
a=23444
print(f'text care contine pe a={a}')

text care contine pe a=23444


In [58]:
a='ceva text'

In [59]:
a[1]

'e'

In [60]:
a[1]='r'

TypeError: 'str' object does not support item assignment

In [61]:
a=4
if a<10:
  print(f'a={a} e mai mic decat 10')
else:
    print ('nu e')

a=4 e mai mic decat 10


In [63]:
print(f'a={a} e mai mic decat 10') if a<10 else print('nu e')

a=4 e mai mic decat 10


In [69]:
a=25
if a<10:
    b=a*5
elif a<20:
    b=a*10
else:
    b=a*15

In [70]:
print(b)

375


In [71]:
c

[1, 2, 3, 5]

In [72]:
for el in c:
    print(el)

1
2
3
5


In [74]:
for index, el in enumerate(c):
    print(index,el)

0 1
1 2
2 3
3 5


In [77]:
list(range(2,10))

[2, 3, 4, 5, 6, 7, 8, 9]

In [78]:
for i in range(10):
    print(i, i**2)

0 0
1 1
2 4
3 9
4 16
5 25
6 36
7 49
8 64
9 81


In [79]:
for i in range(10): print(i, i**2)

0 0
1 1
2 4
3 9
4 16
5 25
6 36
7 49
8 64
9 81


In [80]:
for i in range(10):
    if i<5:
        print(i,i**2)
    else:
        print(i,i**3)

0 0
1 1
2 4
3 9
4 16
5 125
6 216
7 343
8 512
9 729


In [81]:
for i in range(10): print(i,i**2) if i<5 else print(i,i**3)

0 0
1 1
2 4
3 9
4 16
5 125
6 216
7 343
8 512
9 729


## numpy

In [1]:
import numpy as np

In [2]:
a=[1,2,3]

In [3]:
type(a)


list

In [4]:
a=np.array(a)

In [5]:
a

array([1, 2, 3])

In [6]:
type(a)

numpy.ndarray

In [7]:
b=[[1,2,3],[4,5]]

In [8]:
b

[[1, 2, 3], [4, 5]]

In [9]:
c=[[1,2,3],[4,5,6]]

In [10]:
c=np.array(c)

In [11]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b=np.array(b)

C:\Users\maria\AppData\Local\Temp\ipykernel_17136\1349102842.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array(b)


In [99]:
a.shape

(3,)

In [100]:
c.shape

(2, 3)

In [101]:
linii=c.shape[0]

In [102]:
linii

2

In [103]:
coloane=c.shape[1]
coloane

3

In [104]:
a.ndim

1

In [105]:
c.ndim

2

In [106]:
a.dtype

dtype('int32')

In [107]:
d=np.array([1.3, 4, 6])

In [108]:
d.dtype

dtype('float64')

In [109]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
a

array([1, 2, 3])

In [111]:
a[1]

2

In [112]:
c[1]

array([4, 5, 6])

In [113]:
a[1:]

array([2, 3])

In [114]:
a[:1]

array([1])

In [115]:
a[-1]

3

In [116]:
a[-2:]

array([2, 3])

In [117]:
c[1]

array([4, 5, 6])

In [118]:
c[1,-2:]

array([5, 6])

In [119]:
c[:,1]

array([2, 5])

In [120]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
c[:, 1:]

array([[2, 3],
       [5, 6]])

In [122]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [125]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [127]:
np.zeros_like(c)

array([[0, 0, 0],
       [0, 0, 0]])

In [128]:
np.ones(4)

array([1., 1., 1., 1.])

In [129]:
np.ones_like(c)

array([[1, 1, 1],
       [1, 1, 1]])

In [130]:
np.empty(5)

array([1.15980100e-311, 2.20687562e-312, 2.37663529e-312,             nan,
       9.34604358e-307])

In [132]:
np.empty_like(c)

array([[        97, 1635197024,          0],
       [         0,          1,    6029426]])

In [134]:
np.arange(3,10,3)

array([3, 6, 9])

In [135]:
np.arange(30,10,-3)

array([30, 27, 24, 21, 18, 15, 12])

In [138]:
np.full((4,3),[6,1,3])

array([[6, 1, 3],
       [6, 1, 3],
       [6, 1, 3],
       [6, 1, 3]])

In [140]:
np.full_like(c,1000)

array([[1000, 1000, 1000],
       [1000, 1000, 1000]])

In [141]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [142]:
b

array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [144]:
a

array([1, 2, 3])

In [145]:
a+5

array([6, 7, 8])

In [146]:
c+5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [147]:
a*5

array([ 5, 10, 15])

In [148]:
c*5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [149]:
a*a

array([1, 4, 9])

In [150]:
c*c

array([[ 1,  4,  9],
       [16, 25, 36]])

In [151]:
c**3

array([[  1,   8,  27],
       [ 64, 125, 216]], dtype=int32)

In [152]:
c**30

array([[          1,  1073741824, -1010140999],
       [          0,   433305513,  1073741824]], dtype=int32)

In [153]:
2**32

4294967296

In [154]:
9**30

42391158275216203514294433201

In [157]:
a=np.array([1.3,9.4])

In [158]:
a**30

array([2.61999564e+03, 1.56255606e+29])

In [159]:
np.mean(a)

5.3500000000000005

In [160]:
np.mean(c)

3.5

In [161]:
np.mean(c, axis=0)

array([2.5, 3.5, 4.5])

In [162]:
np.mean(c, axis=1)

array([2., 5.])

In [164]:
# np.median, np.sum